version: '3.8'

services:
  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: realtime-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - realtime-network

  # Socket.IO Server
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: realtime-server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - realtime-network
    restart: unless-stopped

  # Next.js Web App
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: realtime-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:8000
    depends_on:
      - server
    networks:
      - realtime-network
    restart: unless-stopped

  # Next.js Docs App
  docs:
    build:
      context: .
      dockerfile: apps/docs/Dockerfile
    container_name: realtime-docs
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - realtime-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  realtime-network:
    driver: bridge
